### PR TITLE
Buffers and Windows

### PR DESCRIPTION
**Pull request by c-taylor**
I have reworded the socket buffer and window scaling sections.
Renamed pacing, and thrown a few topics in with the 'TBD'.

Hope to do more, but Friday got the better of me...

### CODE REVIEW

**Comment by bagder** [comment]
Thanks. [This edit](https://github.com/bagder/I-D/pull/7/commits/bc8a374c3887cbbd9d49d3b596a3f69ddfb5dd94) removes the references to 'max-window' which we have in the appendix. Was that on purpose? If so we need to remove the `net.core.rmem_max` value from the appendix, but it seems that could still be valuable there. Can't it?

**Comment by c-taylor** [comment]
That's me getting markdown upside-down...
It absolutely would; want me to correct and re-submit?

**Comment by moonshiner** [comment]
Hi

Can you correct and re-submit? I'll merge the new version.

thanks

**Comment by c-taylor** [comment]
In hindsight, I'm not certain this is directly an error as described. The reason is I merged setting the maximum into the window scaling scaling as it doesn't need it's own section.

**Comment by c-taylor** [comment]
Ah, got it...incoming...

**Pull request merged**
